version: '3'

services:
  signalling:
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=signalling.curly.im
      - LETSENCRYPT_HOST=signalling.curly.im
      - LETSENCRYPT_EMAIL=taheto@o2.pl
      - VIRTUAL_PORT=80
    networks:
      - webproxy

  auth:
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=auth.curly.im
      - LETSENCRYPT_HOST=auth.curly.im
      - LETSENCRYPT_EMAIL=taheto@o2.pl
      - VIRTUAL_PORT=80
    networks:
      - webproxy

  frontend:
    container_name: frontend
    build: ./frontend/
    environment:
      - VIRTUAL_HOST=curly.im
      - LETSENCRYPT_HOST=curly.im
      - LETSENCRYPT_EMAIL=taheto@o2.pl
      - VIRTUAL_PORT=80
    networks:
      - webproxy

networks:
  webproxy:
    external:
      name: webproxy
