version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ../certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      - proxy-tier

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - ../certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html

  signalling:
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=signalling.curly.im
    networks:
      - proxy-tier

  auth:
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=auth.curly.im
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external:
      name: shared
